### ISSUE TITLE
Return locked and unlocked items independently in search_items

### ISSUE THREAD

**Issue by jkhsjdhjs** [hwchen/secret-service-rs#52]
The current implementation of [`search_items`](https://github.com/hwchen/secret-service-rs/blob/48e759b0258a0d16048a1a075b5d49c0def58df5/src/lib.rs#L282), which performs a `Service.SearchItems` call, returns unlocked and locked items in a single vector. This leaves applications using this library no way of determining which items require unlocking and which do not (besides additional dbus calls of course). Since the function retrieves locked and unlocked items independently, I don't see why it shouldn't return them separately as well.

If this proposal is accepted I'd be happy to provide a PR.

See also: https://github.com/hwchen/keyring-rs/issues/84
/cc @brotskydotcom

**Comment by complexspaces** [comment]
Hey there @jkhsjdhjs. I'd be happy to accept a pull request that implements this change. Regarding the exact API, I'd prefer if it returned a structure with named fields instead of a tuple for clearness, similar to what the raw dbus call returns.

This is also a good time to do so as well because that'd be a breaking change in the API, and `secret-service` is getting ready to cut a 3.0 release to go alongside `zbus`.
